[font]
size = 12.0

[font.bold]
family = "DepartureMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "DepartureMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "DepartureMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "DepartureMono Nerd Font Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0
